services:
  postgres:
    image: postgres:latest
    container_name: tms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tms
    ports:
      - "5432:5432"
    volumes:
      - tms_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: tms_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - tms_redis_data:/data

volumes:
  tms_postgres_data:
  tms_redis_data:
